/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAndController;

import Database.DBProductInterface;
import Database.DBSalesInterface;
import Model.product;
import Model.sales;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import translators.DateList;
import translators.ProductApapter;
import translators.SalesApapter;

/**
 *
 * @author luod1
 */
public class Gui_product_Info extends javax.swing.JFrame {
    
    public static sales sale;
   
    private List<product> list;
    private List<sales> findList;
    private String[] columnTitle = {"Id", "产品编号", "名称", "单位"};

    DBProductInterface productInterface = new ProductApapter();
    DBSalesInterface SalesInterface = new SalesApapter();
    /**
     * Creates new form Gui_purchase
     */
    public Gui_product_Info() {
        
        initComponents();
        quaryAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_info = new javax.swing.JTable();
        jbt_add = new javax.swing.JButton();
        jbt_update = new javax.swing.JButton();
        jbt_delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtf_ProductCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbt_inventory = new javax.swing.JButton();
        jbt_sales = new javax.swing.JButton();
        jbt_purchase = new javax.swing.JButton();
        jbt_earn = new javax.swing.JButton();
        jbt_return = new javax.swing.JButton();
        jbt_other = new javax.swing.JButton();
        jbt_product = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("商品基础");

        jtb_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "产品编号", "名称", "单位"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_info);

        jbt_add.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_add.setText("增加");
        jbt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addActionPerformed(evt);
            }
        });

        jbt_update.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_update.setText("修改");

        jbt_delete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_delete.setText("删除");

        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setText("查找");

        jtf_ProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ProductCodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("输入产品编号：");

        jbt_inventory.setText("商品库存管理");
        jbt_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inventoryActionPerformed(evt);
            }
        });

        jbt_sales.setText("商品销售管理");

        jbt_purchase.setText("商品进货管理");
        jbt_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_purchaseActionPerformed(evt);
            }
        });

        jbt_earn.setText("利润计算");

        jbt_return.setText("退货");

        jbt_other.setText("其他支出");

        jbt_product.setText("添加商品详情");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbt_inventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt_sales)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_purchase)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_earn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_other)
                        .addGap(27, 27, 27)
                        .addComponent(jbt_product)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbt_add)
                .addGap(18, 18, 18)
                .addComponent(jbt_update)
                .addGap(18, 18, 18)
                .addComponent(jbt_delete)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inventory)
                    .addComponent(jbt_sales)
                    .addComponent(jbt_purchase)
                    .addComponent(jbt_earn)
                    .addComponent(jbt_return)
                    .addComponent(jbt_other)
                    .addComponent(jbt_product))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_ProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ProductCodeActionPerformed

    private void jbt_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inventoryActionPerformed
        // TODO add your handling code here:
        new Gui_inventory().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_inventoryActionPerformed

    private void jbt_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_purchaseActionPerformed
        // TODO add your handling code here:
        new Gui_purchase().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_purchaseActionPerformed

    private void jbt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addActionPerformed
        // TODO add your handling code here:
        new Gui_product().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_addActionPerformed

    public void quaryAll() {
        list = productInterface.getAll();
        if (list == null) {
            JOptionPane.showMessageDialog(null, "system error！");
            return;
        }

        Object[][] data = DateList.listToArrayProduct(list);

        DefaultTableModel tableModel = new DefaultTableModel(data, this.columnTitle) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jtb_info.setModel(tableModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_product_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_product_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_product_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_product_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_product_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_add;
    private javax.swing.JButton jbt_delete;
    private javax.swing.JButton jbt_earn;
    private javax.swing.JButton jbt_inventory;
    private javax.swing.JButton jbt_other;
    private javax.swing.JButton jbt_product;
    private javax.swing.JButton jbt_purchase;
    private javax.swing.JButton jbt_return;
    private javax.swing.JButton jbt_sales;
    private javax.swing.JButton jbt_update;
    private javax.swing.JTable jtb_info;
    private javax.swing.JTextField jtf_ProductCode;
    // End of variables declaration//GEN-END:variables
}
