/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAndController;

import Database.DBInventoryInterface;
import Database.DBProductInterface;
import Database.DBPurchaseInterface;
import Database.DBSalesInterface;
import Model.Inventory;
import Model.Purchase;
import Model.sales;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import translators.InventoryApapter;
import translators.ProductApapter;
import translators.PurchaseApapter;
import translators.SalesApapter;

/**
 *
 * @author luod1
 */
public class Gui_OneSale extends javax.swing.JFrame {

   
    public static int rowId;
    DBInventoryInterface InventoryInterface = new InventoryApapter();
    DBSalesInterface SalesInterface = new SalesApapter();
    DBProductInterface productInterface = new ProductApapter();
    /**
     * Creates new form Gui_OnePurchase
     */
    public Gui_OneSale() {
        
        initComponents();
        addlistName();
        addlistCode();
        WarnStock();
        if (Gui_sales.sale != null) {
           
            this.jlb_salePrice.setText(String.valueOf(Gui_sales.sale.getSalePrice()));
            this.jtf_quantity.setText(String.valueOf(Gui_sales.sale.getQuantity()));
            this.jtf_totalSale.setText(String.valueOf(Gui_sales.sale.getTotalsales()));
            this.jDate_Date.setDate(Gui_sales.sale.getDate());
           

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_quantity = new javax.swing.JTextField();
        jtf_totalSale = new javax.swing.JTextField();
        jDate_Date = new com.toedter.calendar.JDateChooser();
        jbt_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbt_cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlb_salePrice = new javax.swing.JLabel();
        jbt_update = new javax.swing.JButton();
        jcb_ProductCode = new javax.swing.JComboBox<>();
        jcb_name = new javax.swing.JComboBox<>();
        jlb_stock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("销售");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("产品编号 *：");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("产品名称 *：");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("销售数量*：");

        jLabel7.setBackground(new java.awt.Color(0, 102, 255));
        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("销售总额*：");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("日期 ：");

        jbt_add.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbt_add.setText("增加新的");
        jbt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addActionPerformed(evt);
            }
        });

        jLabel4.setText("蓝色必填***");

        jbt_cancel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbt_cancel.setText("取消");
        jbt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_cancelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("销售单价：");

        jlb_salePrice.setBackground(new java.awt.Color(0, 153, 255));
        jlb_salePrice.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jbt_update.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbt_update.setText("保存修改");

        jcb_ProductCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_ProductCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_ProductCodeItemStateChanged(evt);
            }
        });

        jcb_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_nameItemStateChanged(evt);
            }
        });

        jlb_stock.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcb_ProductCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                        .addComponent(jbt_cancel))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDate_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_totalSale, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_salePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlb_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jbt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jbt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_cancel)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcb_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jcb_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jlb_salePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_totalSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDate_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_add)
                    .addComponent(jbt_update))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_cancelActionPerformed
        // TODO add your handling code here:
        new Gui_sales().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_cancelActionPerformed

    private void jbt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addActionPerformed
        // TODO add your handling code here:
        try {
            addNew();
            new Gui_sales().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "请注意数据正确添加，蓝色标志为必填");
        }

    }//GEN-LAST:event_jbt_addActionPerformed

    private void jcb_ProductCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_ProductCodeItemStateChanged
        // TODO add your handling code here:
         showName();
         WarnStock();
        
    }//GEN-LAST:event_jcb_ProductCodeItemStateChanged

    private void jcb_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_nameItemStateChanged
        // TODO add your handling code here:
       showCode();
        WarnStock();
    }//GEN-LAST:event_jcb_nameItemStateChanged

     public void addlistName(){
        List<String> list = new ArrayList<String>();
        list =SalesInterface.findName();
        this.jcb_name.setModel(new DefaultComboBoxModel(list.toArray()));
       
    }
    public void addlistCode(){
        List<String> list = new ArrayList<String>();
        list = SalesInterface.findCode();
        this.jcb_ProductCode.setModel(new DefaultComboBoxModel(list.toArray()));
    }
     public void showName() {
        String ProductCode = this.jcb_ProductCode.getSelectedItem().toString();
        String name = SalesInterface.findName(ProductCode);
        List<String> list = new ArrayList<String>();
        list.add(name);
        this.jcb_name.setModel(new DefaultComboBoxModel(list.toArray()));
    }
    
    public void showCode() {
        String name = this.jcb_name.getSelectedItem().toString();
        String code = SalesInterface.findCode(name);
        List<String> list = new ArrayList<String>();
        list.add(code);
        this.jcb_ProductCode.setModel(new DefaultComboBoxModel(list.toArray()));
    }
    public void WarnStock() {
        String ProductCode = this.jcb_ProductCode.getSelectedItem().toString();
        Inventory y = InventoryInterface.findOne(ProductCode);
        
        String s = String.valueOf(y.getStock());
        this.jlb_stock.setText("当前库存数量：" +s);
    }
    
    public boolean addNew() {
       String ProductCode = this.jcb_ProductCode.getSelectedItem().toString();
        String name = this.jcb_name.getSelectedItem().toString();

        int quantity = Integer.parseInt(this.jtf_quantity.getText());
       
        Date Date = this.jDate_Date.getDate();
        
        BigDecimal q = new BigDecimal(quantity);
        BigDecimal totalsales = new BigDecimal(this.jtf_totalSale.getText());
        BigDecimal salePrice = totalsales.divide(q);
        
        Inventory y = InventoryInterface.findOne(ProductCode);
        
        
        
        BigDecimal purchase = y.getAverageCost().multiply(q);
        BigDecimal pofits = totalsales.subtract(purchase);
        
        sales sale = new sales(ProductCode, name, salePrice,  quantity, totalsales,Date,  pofits);

        boolean insert = SalesInterface.addSales(sale);

        if (insert) {
            int stock =  y.getStock() - quantity;
            Inventory newY = new Inventory(y.getProductCode(),y.getName(),y.getUnit(),stock,y.getRecentPurchasePrice(),y.getAverageCost(),y.getStoreDate());
            InventoryInterface.updatePurchase(newY);
            
            JOptionPane.showMessageDialog(null, "insert success!");
            new Gui_sales().quaryAll();
            
            this.jlb_salePrice.setText("");
            this.jtf_quantity.setText("");
            this.jtf_totalSale.setText("");
            this.jDate_Date.setDate(null);
            

        } else {
            JOptionPane.showMessageDialog(null, "fail to save!");
        }
        return insert;
    }

    private void update() {
        int id = Gui_OneSale.rowId;
       String ProductCode = this.jcb_ProductCode.getSelectedItem().toString();
       String name = this.jcb_name.getSelectedItem().toString();

        int quantity = Integer.parseInt(this.jtf_quantity.getText());
       
        Date Date = this.jDate_Date.getDate();
        
        BigDecimal q = new BigDecimal(quantity);
        BigDecimal totalsales = new BigDecimal(this.jtf_totalSale.getText());
        BigDecimal salePrice = totalsales.divide(q);
        
        Inventory y = InventoryInterface.findOne(ProductCode);
        
        BigDecimal purchase = y.getAverageCost().multiply(q);
        BigDecimal pofits = totalsales.subtract(purchase);
        
        sales sale = new sales(id,ProductCode, name, salePrice,  quantity, totalsales,Date,  pofits);
        //update the habits information at database
        boolean update = SalesInterface.updateSales(sale);
        if (update) {
            JOptionPane.showMessageDialog(null, "modify success!");
            Gui_sales.sale = null;
            
            this.jlb_salePrice.setText("");
            this.jtf_quantity.setText("");
            this.jtf_totalSale.setText("");
            this.jDate_Date.setDate(null);
            this.rowId = 0;
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "modify fail!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_OneSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_OneSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_OneSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_OneSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_OneSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDate_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbt_add;
    private javax.swing.JButton jbt_cancel;
    private javax.swing.JButton jbt_update;
    private javax.swing.JComboBox<String> jcb_ProductCode;
    private javax.swing.JComboBox<String> jcb_name;
    private javax.swing.JLabel jlb_salePrice;
    private javax.swing.JLabel jlb_stock;
    private javax.swing.JTextField jtf_quantity;
    private javax.swing.JTextField jtf_totalSale;
    // End of variables declaration//GEN-END:variables
}
