/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAndController;

import Database.DBSalesInterface;
import Model.sales;
import java.awt.FileDialog;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import translators.DateList;
import translators.ExcelFile;
import translators.SalesApapter;

/**
 *
 * @author luod1
 */
public class Gui_sales extends javax.swing.JFrame {
    
    public static sales sale;
   
    private List<sales> list;
    private List<sales> findList;
    private String[] columnTitle = {"Id", "产品编号", "名称", "销售单价","销售数量","销售总额","日期","利润"};

    
    DBSalesInterface SalesInterface = new SalesApapter();
    /**
     * Creates new form Gui_purchase
     */
    public Gui_sales() {
        initComponents();
        
        quaryAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_sale = new javax.swing.JTable();
        jbt_add = new javax.swing.JButton();
        jbt_update = new javax.swing.JButton();
        jbt_delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtf_ProductCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbt_inventory = new javax.swing.JButton();
        jbt_sales = new javax.swing.JButton();
        jbt_purchase = new javax.swing.JButton();
        jbt_earn = new javax.swing.JButton();
        jbt_other = new javax.swing.JButton();
        jbt_product = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JDate_day = new com.toedter.calendar.JDateChooser();
        JMonth_choose = new com.toedter.calendar.JMonthChooser();
        jbt_MonthFind = new javax.swing.JButton();
        jbt_DayFind = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbt_exportExcel2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("销售管理");

        jtb_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "产品编号", "名称", "销售单价", "销售数量", "销售总额", "日期", "利润"
            }
        ));
        jScrollPane1.setViewportView(jtb_sale);

        jbt_add.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_add.setText("增加");
        jbt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addActionPerformed(evt);
            }
        });

        jbt_update.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_update.setText("修改");

        jbt_delete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_delete.setText("删除");

        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setText("查找");

        jtf_ProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ProductCodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("输入产品编号：");

        jbt_inventory.setText("商品库存管理");
        jbt_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inventoryActionPerformed(evt);
            }
        });

        jbt_sales.setText("商品销售管理");

        jbt_purchase.setText("商品进货管理");
        jbt_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_purchaseActionPerformed(evt);
            }
        });

        jbt_earn.setText("利润计算");

        jbt_other.setText("其他支出与退货");

        jbt_product.setText("添加商品详情");
        jbt_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_productActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("输入日期查找：");

        jbt_MonthFind.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbt_MonthFind.setText("查找");
        jbt_MonthFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_MonthFindActionPerformed(evt);
            }
        });

        jbt_DayFind.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbt_DayFind.setText("查找");
        jbt_DayFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_DayFindActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("按月份查找：");

        jbt_exportExcel2.setText("导出EXCEL");
        jbt_exportExcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_exportExcel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_ProductCode, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jbt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(JDate_day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jbt_DayFind)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JMonth_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbt_MonthFind)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbt_inventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt_sales)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_purchase)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_earn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbt_other)
                        .addGap(44, 44, 44)
                        .addComponent(jbt_product)
                        .addGap(49, 49, 49)
                        .addComponent(jbt_exportExcel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(84, 84, 84))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbt_add)
                .addGap(18, 18, 18)
                .addComponent(jbt_update)
                .addGap(18, 18, 18)
                .addComponent(jbt_delete)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtf_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JDate_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_DayFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(JMonth_choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbt_MonthFind)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inventory)
                    .addComponent(jbt_sales)
                    .addComponent(jbt_purchase)
                    .addComponent(jbt_earn)
                    .addComponent(jbt_other)
                    .addComponent(jbt_product)
                    .addComponent(jbt_exportExcel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_ProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ProductCodeActionPerformed

    private void jbt_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inventoryActionPerformed
        // TODO add your handling code here:
        new Gui_inventory().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_inventoryActionPerformed

    private void jbt_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_purchaseActionPerformed
        // TODO add your handling code here:
        new Gui_purchase().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_purchaseActionPerformed

    private void jbt_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_productActionPerformed
        // TODO add your handling code here:
        new Gui_product_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_productActionPerformed

    private void jbt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addActionPerformed
        // TODO add your handling code here:
        new Gui_OneSale().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_addActionPerformed

    private void jbt_exportExcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_exportExcel2ActionPerformed
        // TODO add your handling code here:
        FileDialog fd = new FileDialog(this, "保存产品销售记录", FileDialog.SAVE);
        fd.setVisible(true);
        String stringfile = fd.getDirectory() + fd.getFile() + ".xls";
        try {
            ExcelFile export = new ExcelFile();
            export.exportTable(this.jtb_sale, new File(stringfile));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbt_exportExcel2ActionPerformed

    private void jbt_DayFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_DayFindActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbt_DayFindActionPerformed

    private void jbt_MonthFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_MonthFindActionPerformed
        // TODO add your handling code here:
        findMonth();
       
    }//GEN-LAST:event_jbt_MonthFindActionPerformed

    public void findMonth(){
        List<sales> listMonth = new ArrayList<sales>();
        int a = this.JMonth_choose.getMonth()+1;
        listMonth = SalesInterface.findMonth(a);
        if (listMonth == null) {
            JOptionPane.showMessageDialog(null, "system error！");
            return;
        }
        Object[][] data = DateList.listToArraySales(listMonth);
        DefaultTableModel tableModel = new DefaultTableModel(data, this.columnTitle) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jtb_sale.setModel(tableModel);
        
    }
    public void quaryAll() {
        list = SalesInterface.getAll();
        if (list == null) {
            JOptionPane.showMessageDialog(null, "system error！");
            return;
        }

        Object[][] data = DateList.listToArraySales(list);

        DefaultTableModel tableModel = new DefaultTableModel(data, this.columnTitle) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jtb_sale.setModel(tableModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDate_day;
    private com.toedter.calendar.JMonthChooser JMonth_choose;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_DayFind;
    private javax.swing.JButton jbt_MonthFind;
    private javax.swing.JButton jbt_add;
    private javax.swing.JButton jbt_delete;
    private javax.swing.JButton jbt_earn;
    private javax.swing.JButton jbt_exportExcel2;
    private javax.swing.JButton jbt_inventory;
    private javax.swing.JButton jbt_other;
    private javax.swing.JButton jbt_product;
    private javax.swing.JButton jbt_purchase;
    private javax.swing.JButton jbt_sales;
    private javax.swing.JButton jbt_update;
    private javax.swing.JTable jtb_sale;
    private javax.swing.JTextField jtf_ProductCode;
    // End of variables declaration//GEN-END:variables
}
