/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiAndController;

import Database.DBInventoryInterface;
import Model.Inventory;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import translators.DateList;
import translators.InventoryApapter;

/**
 *
 * @author luod1
 */
public class Gui_inventory extends javax.swing.JFrame {
    
    public static Inventory inventory;
    private List<Inventory> list;
    private List<Inventory> findList;
    private String[] columnTitle={"Id", "产品编号", "名称,", "单位","库存数量","最近进价", "库存成本均价","最近入库日期"};
    DBInventoryInterface InventoryInterface = new InventoryApapter();
    /**
     * Creates new form Gui_purchase
     */
    public Gui_inventory() {
        initComponents();
        showAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_inventory = new javax.swing.JTable();
        jbt_add = new javax.swing.JButton();
        jbt_update = new javax.swing.JButton();
        jbt_delete = new javax.swing.JButton();
        jbt_find = new javax.swing.JButton();
        jtf_ProductCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbt_inventory = new javax.swing.JButton();
        jbt_sales = new javax.swing.JButton();
        jbt_purchase = new javax.swing.JButton();
        jbt_earn = new javax.swing.JButton();
        jbt_return = new javax.swing.JButton();
        jbt_other = new javax.swing.JButton();
        jbt_product = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("库存管理");

        jtb_inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "产品编号", "名称", "单位", "库存数量", "最近进价", "库存成本均价", "进货日期", "最近入库日期"
            }
        ));
        jScrollPane1.setViewportView(jtb_inventory);

        jbt_add.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_add.setText("增加");

        jbt_update.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_update.setText("修改");

        jbt_delete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_delete.setText("删除");

        jbt_find.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbt_find.setText("查找");
        jbt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_findActionPerformed(evt);
            }
        });

        jtf_ProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ProductCodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("输入产品编号：");

        jbt_inventory.setText("商品库存管理");

        jbt_sales.setText("商品销售管理");
        jbt_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salesActionPerformed(evt);
            }
        });

        jbt_purchase.setText("商品进货管理");
        jbt_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_purchaseActionPerformed(evt);
            }
        });

        jbt_earn.setText("利润计算");

        jbt_return.setText("退货");

        jbt_other.setText("其他支出");

        jbt_product.setText("添加商品详情");
        jbt_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbt_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_purchase)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_earn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_return, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_other)
                        .addGap(27, 27, 27)
                        .addComponent(jbt_product)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_inventory)
                            .addComponent(jbt_sales)
                            .addComponent(jbt_purchase)
                            .addComponent(jbt_earn)
                            .addComponent(jbt_return)
                            .addComponent(jbt_other)
                            .addComponent(jbt_product))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jbt_add)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_update)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_delete)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_ProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt_find)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_ProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ProductCodeActionPerformed

    private void jbt_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_purchaseActionPerformed
        // TODO add your handling code here:
        new Gui_purchase().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_purchaseActionPerformed

    private void jbt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_findActionPerformed
        // TODO add your handling code here:
        this.find();
    }//GEN-LAST:event_jbt_findActionPerformed

    private void jbt_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salesActionPerformed
        // TODO add your handling code here:
        new Gui_sales().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_salesActionPerformed

    private void jbt_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_productActionPerformed
        // TODO add your handling code here:
         new Gui_product_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_productActionPerformed

    public void showAll(){
        list = InventoryInterface.getAll();
        
        if (list == null) {
            JOptionPane.showMessageDialog(null, "system error！");
            return;
        }
        
        Object[][] data = DateList.listToArrayInventory(list);
        
        
        DefaultTableModel tableModel = new DefaultTableModel(data, this.columnTitle) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jtb_inventory.setModel(tableModel);
    }
    
    private void find(){
        findList = InventoryInterface.findInventory(this.jtf_ProductCode.getText());
        if (findList == null) {
            JOptionPane.showMessageDialog(null, "system error！");
            return;
        }
        Object[][] data = DateList.listToArrayInventory(findList);

        DefaultTableModel tableModel = new DefaultTableModel(data, this.columnTitle) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.jtb_inventory.setModel(tableModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_add;
    private javax.swing.JButton jbt_delete;
    private javax.swing.JButton jbt_earn;
    private javax.swing.JButton jbt_find;
    private javax.swing.JButton jbt_inventory;
    private javax.swing.JButton jbt_other;
    private javax.swing.JButton jbt_product;
    private javax.swing.JButton jbt_purchase;
    private javax.swing.JButton jbt_return;
    private javax.swing.JButton jbt_sales;
    private javax.swing.JButton jbt_update;
    private javax.swing.JTable jtb_inventory;
    private javax.swing.JTextField jtf_ProductCode;
    // End of variables declaration//GEN-END:variables
}
